version: '3'
services:
  api:
    build:
      context: ./docker
      target: ${TARGET:-dev}
    networks:
      - combo_agency
    working_dir: /app
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - ${PWD:-./}:/${TARGET:-app}
      - ${PWD:-./}/docker/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 8083:8083
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: mariadb:10.9.2
    networks:
      - combo_agency
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    command: sh -c 'echo "[client]\nuser=root\npassword=${DB_PASSWORD}" > /root/.my.cnf && docker-entrypoint.sh mysqld'
    volumes:
      - "${PWD:-./}:/app"
      - "dbdata:/var/lib/mysql"
  redis:
    image: redis:latest
    networks:
      - combo_agency
    ports:
      - 6379:6379
    command: redis-server --requirepass secret
networks:
  combo_agency:
volumes:
  dbdata:
